"resources"
{
"maps/ff_bunkerwars.bsp" "file"
"maps/ff_bunkerwars.res" "file"
"maps/ff_bunkerwars.lua" "file"
"maps/ff_bunkerwars.txt" "file"
"maps/ff_bunkerwars_level_sounds.txt" "file"
"materials/vgui/loadingscreens/ff_bunkerwars.vtf" "file"
"materials/vgui/loadingscreens/ff_bunkerwars.vmt" "file"
"materials/skybox/space_01bk.vmt" "file"
"materials/skybox/space_01bk.vtf" "file"
"materials/skybox/space_01dn.vmt" "file"
"materials/skybox/space_01dn.vtf" "file"
"materials/skybox/space_01ft.vmt" "file"
"materials/skybox/space_01ft.vtf" "file"
"materials/skybox/space_01lf.vmt" "file"
"materials/skybox/space_01lf.vtf" "file"
"materials/skybox/space_01rt.vmt" "file"
"materials/skybox/space_01rt.vtf" "file"
"materials/skybox/space_01up.vmt" "file"
"materials/skybox/space_01up.vtf" "file"
"sound/ff_sc/tdrTra00.wave" "file"
"sound/ff_sc/tdrTra01.wave" "file"
}